spring:
  application:
    name: CART-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/cart_service
    username: root
    password: 2000
  jpa:
    hibernate:
      ddl-auto: update
    sql-show: true

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost